title: Test site

sidebar:
  - index
  - label: Topic 1
    children:
    - page1
    - page2
  - label: Topic 2
    children:
    - page3
  - about

url: "https://mkreyesh.github.io" 
baseurl: "/DocTemplate" 

search_enabled: true
auto_page_title: true

remote_theme: zendesk/jekyll-theme-zendesk-garden@v0.7.3

plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    enable_dollar_delimiter: true